version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    overwrite: yes
permission:
  - object: /
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/after.sh
      timeout: 300
      runas: ec2-user