version: 0.0
os: linux
files:
  - source: /build/libs/boriPaw-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user
permission:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/after.sh
      timeout: 300
      runas: ec2-user