version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: local_db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3367:3306"
  redis:
    image: redis:6
    ports:
      - "6364:6379"