server:
  servlet:
    encoding:
      force-response: true
  host: localhost

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3366/test_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6363
      database: 0
logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG

secrete:
  secrete_key: "fsafnslkdasdkladmkgpeiakmggsdklkgewmkglsgiwwlgwefds"
  accessTokenLifeMillieSeconds: 600000
  refreshTokenLifeMillieSeconds: 604800000
  encoder:
    key: "asfsaklmasfapfqwpignpqgkqfkmwasdjndsjlfsdklfamklfaf3525fasfasfsafa"
    iv: "asfsaklmasfapfqwpignpqgkqfkmwasdjndsjlfsdklfamklfaffsaghadhdfhfdah"