spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3366/test_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6363
      database: 0 # Redis 데이터베이스 인덱스
